# Generated by Django 5.0.6 on 2024-06-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='token',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='booked_time',
            new_name='appointment_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='available_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
