# Generated by Django 5.0.6 on 2024-06-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_speciality_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='specialty_images/'),
        ),
    ]
