# Generated by Django 5.0.6 on 2024-06-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.speciality'),
        ),
    ]
