# Generated by Django 5.0.6 on 2024-06-12 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_doctor_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='special',
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.profession'),
        ),
    ]
