# Generated by Django 5.0.6 on 2024-06-14 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_remove_appointment_available_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.speciality'),
        ),
    ]
