# Generated by Django 5.0.6 on 2024-06-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='speciality',
            new_name='specialty',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
