# Generated by Django 5.0.6 on 2024-07-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_remove_appointment_doctor_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
                ('interval', models.IntegerField(default=4000)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('image', models.ImageField(upload_to='services/')),
                ('badge', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
